name = "DataSci4Chem"
uuid = "ad2afb88-707b-4870-bda2-735669810ff9"
authors = ["Saer Samanipour, PhD", "Env Modeling & Computational Mass Spec Lab (EMCMS)"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
